### ISSUE TITLE
Possible to use it with Kinetic Kame? - rosparam not working

### ISSUE THREAD

**Issue by HWiese1980** [roshub/vapor_master#21]
Hi, is it possible to run vapor-master with ROS Kinetic Kame? Or are there known incompatibilities regarding the used protocols?

Thanks

**Comment by sevenbitbyte** [comment]
There are no known issues, though we have primarily tested against Melodic. But everything should work if you simply place the vapor-master repo into your catkin workspace and compile as normal.

## Potential nodejs issue

The most likely problem is to be nodejs/yarn availability for your OS version rather than direct ROS issues.

If you're running an [OS supported by Ubuntu Snap](https://docs.snapcraft.io/installing-snapd/6735) we strongly recommend simply installing our [snap package in the snap store](https://snapcraft.io/vapor-master).

### Development setups

I'd recommend following the directions provided by NodeSource for installing modern versions of nodejs/npm/yarn on your OS via their package repo. See -> https://github.com/nodesource/distributions

We typically run these versions:

* yarn       1.12.3
* npm       6.4.1
* nodejs   v8.12.0

The mainline debian/Ubuntu nodejs packages are very old. You can however still run vapor-master on those old nodejs versions, we already have all the scripts in place needed to build via Catkin. 

Starting via `yarn start` is likely to fail on nodejs versions older than 6.x but running `nodejs run prepare-catkin` then `./bin/vapor-master` should work on old nodejs versions.

### Conclusion

Give it a try, there are various approaches that should work. Let us know if you run into trouble.

@HWiese1980

**Comment by HWiese1980** [comment]
I have built it from a catkin workspace and successfully started it, though I have some issues with the parameter server. It seems, at a first glance, that ther have been some changes in the API... I could be wrong though. Please see my comment on discourse.ros.org: https://discourse.ros.org/t/vapor-master-a-distributed-high-availability-rosmaster/7375/4

**Comment by NickZ** [comment]
I can confirm this bug, and it seems to happen across all distros. I am working on a fix for this.

**Comment by sevenbitbyte** [comment]
we've merged a fix [here](https://github.com/roshub/vapor_master/pull/22) and have deployed to [the snap store](https://snapcraft.io/vapor-master).

You can update your installation with:

`snap refresh vapor-master`
